[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "ftests"
optimizer = true
optimizer_runs = 200
solc = "0.8.17"
remappings = ["@openzeppelin/contracts=lib/OpenZeppelin/openzeppelin-contracts@4.8.3/contracts",
    "@openzeppelin/contracts-upgradeable=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts",
    "@celer-network/contracts=lib/celer-network/sgn-v2-contracts-main/contracts"]